#!/usr/bin/env bash
#Script displays numbers 1 to 100. Displays "FizzBuzz" when the number is 3 and 5.
#"Fizz" when the number is a mulitple of 3. "Buzz" if a multiple of 5.
count=1
while [ $count -lt 101 ]
do
	if (( count%3 == 0 && count%5 == 0 )); then
		echo "FizzBuzz";
	else
		if (( count%3 == 0 )); then
			echo "Fizz"
		elif (( count%5 == 0 )); then
			echo "Buzz"
		else
			echo $count
		fi
	fi
	count=$((count + 1))
done
