#!/usr/bin/env bash
#A bash script that prints the content of the file /etc/passwd
while IFS=: read -r username uid home; do
	echo "Username: $username, UID: $uid, Home Directory: $home"
done < /etc/passwd
