#!/usr/bin/env bash
# Loop through all non-hidden files in the current directory
for file in $(ls -p | grep -v /); do
    if [[ "$file" == *-* ]]; then
        new_name="${file#*-}"
        echo "$new_name"
    else
        echo "$file"
    fi
done

