#!/usr/bin/env bash
# Bash script that prints a list of currently running processes.
ps -e --forest -o uid,cmd | awk 'BEGIN { OFS=" "; } NR==1 { print "UID", "COMMAND"; next } { print $1, substr($0, index($0, $2)) }'
