#!/usr/bin/env bash
# Bash script that prints a list of currently running processes.
if ! command -v pstree &> /dev/null
then
    echo "pstree is not installed. Installing..."
    sudo apt-get install -y psmisc
fi

echo "Listing all running processes in a hierarchical format:"
pstree -A -p

echo -e "\nDetailed process listing:"

ps -e -o user,pid,ppid,tty,stat,start,time,%cpu,%mem,vsz,rss,cmd --sort=ppid
