#!/usr/bin/env bash
# Stop the process running the script '4-to_infinity_and_beyond without using kill or killall
pid=$(pgrep -f "7-highlander")

# Check if the process exists
if [[ -n "$pid" ]]; then
    echo "SIGTERM" > "/proc/$pid/status" 2>/dev/null || pkill -f "7-highlander"
else
    echo "Process not found."
fi
